#!/bin/bash

# If the --init flag is set, this is a new system and we need to get all dependencies. 
if [[ $* == *--init* ]]
  then
    # Get all required packages from the arch package databases and install them
    sudo aura -Sy gvim
    # Get all required packages from the AUR
    sudo aura -Ay vim-pathogen
    # Update submodules
    cd $PWD
    git submodule update --init
fi


# Remove any existing versions of the files

# vim
rm -f ~/.vimrc
rm -Rf ~/.vim

# jshint
rm -f ~/.jshintrc

# Symlink to the new files

# vim
ln -s $PWD/vim/vimrc ~/.vimrc
ln -s $PWD/vim/vim ~/.vim

# jshint
ln -s $PWD/jshintrc ~/.jshintrc
