#!/bin/bash

# Remove any existing versions of the files

# Awesome WM Config
rm -Rf ~/.config/awesome

# .bashrc
rm -f ~/.bashrc

# .xprofile
rm -f ~/.xprofile

# .Xresources
rm -f ~/.Xresources

# vim
rm -f ~/.vimrc
rm -Rf ~/.vim

# Symlink to the new files

# Awesome WM Config
ln -s $PWD/awesome/ ~/.config/awesome

# .bashrc
ln -s $PWD/bash/bashrc ~/.bashrc

# .xprofile
ln -s $PWD/x/xprofile ~/.xprofile

# .Xresources
ln -s $PWD/x/Xresources ~/.Xresources

# vim
ln -s $PWD/vim/vimrc ~/.vimrc
ln -s $PWD/vim/vim ~/.vim
