" Pathogen
call pathogen#infect()
" Colour syntax highlighting
syntax enable 
" File type based indentation
filetype plugin indent on
" Solarized colourscheme
set background=dark
colorscheme solarized
" 256 colour mode
set t_Co=256
" Get rid of the menus and scroll bars in gVim
set guioptions-=m
set guioptions-=T
set guioptions-=r
set guioptions-=L
" Always show the status line
set laststatus=2
" Set the font
set guifont=Droid\ Sans\ Mono\ for\ Powerline\ 10
" Turn Powerline symbols on
let g:airline_powerline_fonts = 1
" Set indentation to 2 spaces
set shiftwidth=2
" Set tabs to be 2 spaces
set tabstop=2
" Expand all tab characters to 2 spaces
set expandtab
