#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Set the default prompt
PS1='[\u@\h \W]\$ '

# Start tmux by default
if [[ ! $TERM =~ screen ]]; then
    exec tmux
fi
